### ISSUE TITLE
Add logout button in all admin views

### ISSUE THREAD

**Issue by anapaulagomes** [anapaulagomes/to-vendendo#38]
Currently the logout button is shown just in the Home. 

<img width="1203" alt="screen shot 2017-10-06 at 09 24 50" src="https://user-images.githubusercontent.com/1899950/31277959-a6363e8c-aa79-11e7-9717-d20b00777d38.png">

This issue is to add the logout button in all admin views (Item, User, Category).

<img width="1183" alt="screen shot 2017-10-06 at 09 25 05" src="https://user-images.githubusercontent.com/1899950/31277960-a63660c4-aa79-11e7-8897-76cb84c66b1e.png">

**Comment by tchaguitos** [comment]
Hey, I can do it!

**Comment by anapaulagomes** [comment]
Hey I'm work on it (with Docker etc). But can you be more specific about the problem?

**Comment by tchaguitos** [comment]
I think my pull request solves the problem, but can not test in my pc :(

**Comment by anapaulagomes** [comment]
Let's talk on [Gitter](https://gitter.im/to-vendendo/Lobby) to figure out!

**Comment by a-arpit94** [comment]
I find the same bug so solved it, later I saw there's an open issue for it. 
So, I made the pull request #46
